name: Continuous Integration
on: push

jobs:
  set-up:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        env:
          HSEDUCK_BOT_ADMIN_ID: ${{ secret.HSEDUCK_BOT_ADMIN_ID }}
          HSEDUCK_BOT_IEXAPI_TOKEN_SANDBOX: ${{ secret.HSEDUCK_BOT_IEXAPI_TOKEN_SANDBOX }}
          HSEDUCK_BOT_IEXAPI_TOKEN_SECRET: ${{ secret.HSEDUCK_BOT_IEXAPI_TOKEN_SECRET }}
          HSEDUCK_BOT_TELEGRAM_TOKEN: ${{ secret.HSEDUCK_BOT_TELEGRAM_TOKEN }}
      - run: |
          make run