name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  set-up:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: make init