name: Continuous Integration
on:
  push:
    branches:
      - main

jobs:
  set-up:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - env:
          HSEDUCK_BOT_ADMIN_ID: ${{ secrets.HSEDUCK_BOT_ADMIN_ID }}
          HSEDUCK_BOT_IEXAPI_TOKEN_SANDBOX: ${{ secrets.HSEDUCK_BOT_IEXAPI_TOKEN_SANDBOX }}
          HSEDUCK_BOT_IEXAPI_TOKEN_SECRET: ${{ secrets.HSEDUCK_BOT_IEXAPI_TOKEN_SECRET }}
          HSEDUCK_BOT_TELEGRAM_TOKEN: ${{ secrets.HSEDUCK_BOT_TELEGRAM_TOKEN }}
        run: make run